name: arena-watcher

services:
  arena-watcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arena-watcher
    restart: unless-stopped
    labels:
      - "com.dozzle.enable=true"
      - "com.dozzle.group=Bots"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    volumes:
      - ./config/appsettings.json:/app/config/appsettings.json:ro
      - ./data:/app/data
